________________________________________________
v0.06
[-] Added Steal players Engines
[-] Added Steal Wheels
[-] Added Steal Tyres
[-] Added Hitchhiker Chaos
[-] Added Car Magent
[-] Added Lexis Crashes
________________________________________________
v0.07
[-] Added Zombies Survival Mode
[-] Added Ride skateboard
[-] Added Ride surfboard
[-] Added Spawn Objects (Custom offsets)
[-] Added DeSync Doctor
[-] Added Vehicle Attachments
[!] Fixed Bugs with clone centipede
