________________________________________________
v0.04
[-] Added credits to CoalwiX
[-] Added FSL Money
[-] Added cargobob kidnap
[-] Added cargobob confiscate
[-] Added push player up
[-] Added metro madness
[-] Added drunk pilot
[-] Added garage doors troll
[-] Added nuke
[-] Added bri''ish attacker
[-] Added sirens all nearby players
[-] Added kill all engines
[-] Added remove wheels
[-] Added all cars sink
[-] Added honk all cars
[-] Added fuck up all cars
[-] Added destruction (map cars troll)
[-] Added fly nearby vehicles
[-] Added bounce nearby vehicles
[-] Added 360 nearby vehicles
[-] Added 360 Self vehicle
[-] Added spinbot nearby vehicles
[-] Added all vehicles pink
[-] Added all vehicles rainbow
[-] Added invisible peds
[-] Added spinbot peds
[-] Added spinbot self ped
[-] Added explode map
[-] Added block entrances
[-] Added tornado
[-] Added tornado 2.0
[!] Removed aalib.dll (Bruh sound on lua startup) to remove flagged false positives when installing ________________________________________________
[!] Report any Bugs/Broken features on the Discord
