________________________________________________
v0.09
[-] Added all stands kicks & crashes to get to them faster
[!] Fixed bug with ride a skateboard not working (Still has the floating bug)
[!] Fixed bugs with steal all 4 wheels (works on players now)
[!] Fixed bugs with remove wheels (added radius slider)
[!] Fixed bugs with change log
[!] Fixed bugs with error on load with internet access enabled on addict
[!] Fixed bugs with drive a cop car
[!] Fixed bugs with tp options
[!] Removed old crashes
[!] Changed lexis crashes around and renamed them slightly
________________________________________________
v0.07
[-] Added Zombies Survival Mode
[-] Added Ride skateboard
[-] Added Ride surfboard
[-] Added Spawn Objects (Custom offsets)
[-] Added DeSync Doctor
[-] Added Vehicle Attachments
[!] Fixed Bugs with clone centipede
________________________________________________
v0.06
[-] Added Steal players Engines
[-] Added Steal Wheels
[-] Added Steal Tyres
[-] Added Hitchhiker Chaos
[-] Added Car Magent
[-] Added Lexis Crashes
